CREATE TABLE CLIENTES (
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	IDADE INT NOT NULL
	);

	INSERT INTO CLIENTES(CPF, NOME, IDADE)
	VALUES('11122233344', 'Amanda Azeredo', 21);
	
	INSERT INTO CLIENTES(CPF, NOME, IDADE)
	VALUES('11122233355', 'Andre Santos', 30);

CREATE TABLE TELEFONES(
	CPF_CLIENTE VARCHAR(11),
	DDD VARCHAR(2),
	TELEFONE VARCHAR(9),
	PRIMARY KEY (CPF_CLIENTE),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF)
	);

	INSERT INTO TELEFONES(CPF_CLIENTE, DDD, TELEFONE)
	VALUES('11122233344', '21', '995537938');
	
	INSERT INTO TELEFONES(CPF_CLIENTE, DDD, TELEFONE)
	VALUES('11122233355', '21', '999888765');

	SELECT * FROM CLIENTES
	SELECT * FROM TELEFONES

	SELECT NOME FROM CLIENTES WHERE IDADE >= 22 ORDER BY IDADE ASC;

	SELECT C.NOME, COUNT(T.CPF_CLIENTE) AS QTD_TELEFONES FROM CLIENTES C
	LEFT JOIN TELEFONES T ON C.CPF = T.CPF_CLIENTE
	GROUP BY C.NOME
	HAVING COUNT(T.CPF_CLIENTE) >= 1;

	DELETE FROM TELEFONES WHERE CPF_CLIENTE IN (SELECT CPF FROM CLIENTES WHERE NOME LIKE '% santos');
	DELETE FROM CLIENTES WHERE NOME LIKE '% santos';




	